config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'superpowers#index'
 # get '/superpowers', to: 'superpowers#index'
 # get '/superpowers/new', to: 'superpowers#new'
 # post '/superpowers', to: 'superpowers#create'
  get '/users/:id', to: 'users#show', as: :user
  get '/dashboard', to: 'pages#dashboard'

  resources :superpowers do
    resources :rents, only: [:create, :show, :index]
  end
  resources :rents, only: [:destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :superpower
  belongs_to :user
  validates :date_from, presence: true
  validates :date_to, presence: true
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  has_many :rents
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  geocoded_by :location
  after_validation :geocode
  include PgSearch::Model
  pg_search_scope :srch,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :superpowers
  has_many :rents
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @superpowers = current_user.superpowers
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    @rents = Rent.where(user: current_user)
  end

  #to make a reservation
  def create
    @superpower = Superpower.find(params[:superpower_id])
    @rent = Rent.new(rent_params)
    @rent.user = current_user
    @rent.superpower = @superpower
    if @rent.save!
      redirect_to superpower_rents_path, notice: "Your power was booked!"
    else
      render "superpowers/show"
    end
  end

  def update
    @rent = Rent.find(params[:id])
    @rent.status = true
    if @rent.save!
      redirect_to dashboard_path, notice: "Power confirmed!"
    else
      render "dashboard"
    end
  end

  #to cancel a reservation
  def destroy
    @rent = Rent.find(params[:id])
    @superpower = @rent.superpower
    @rent.destroy
    redirect_to superpower_rents_path(@superpower), notice: "Power deleted"
  end

  private

  def rent_params
    params.require(:rent).permit(:date_from, :date_to)
  end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  before_action :set_superpower, only: [:show, :edit, :update, :destroy]

  def new
    @superpower = Superpower.new
  end

  def create
    user = current_user
    @superpower = Superpower.new(superpower_params)
    @superpower.user = user
    if @superpower.save
      redirect_to superpowers_path
    else
      render :new
    end
  end

  def index
    @superpowers = Superpower.all
    @superpowers = Superpower.srch(params[:query]) if params[:query].present?
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @superpowers.geocoded.map do |superpower|
      {
        lat: superpower.latitude,
        lng: superpower.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { superpower: superpower }),
      }
    end
  end

  def show
    # set_superpower already included because of before_action where it's connected to show
    # display one superpower
    # no code needed due to set_superpower
    @rent = Rent.new
  end

  def edit
    # set_superpower is already (similar to show)
    # in view being edited and then used in update
  end

  def update
    # don't forget to make the update method and to check if it's included in before_action!
    if @superpower.update(superpower_params)
      redirect_to superpower_path(@superpower)
    else
      render :edit
    end
  end

  def destroy
    # set_superpower finds it
    # deleting it
    # redirect
    @superpower.destroy
    redirect_to superpowers_path
  end

  private

  def set_superpower
    @superpower = Superpower.find(params[:id])
  end

  def superpower_params
    params.require(:superpower).permit(:name, :price, :description, :photo, :location, :coordinates)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super Doom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>

    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload", defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
      <%= render "shared/flashes" %>
   </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>The Powers you have up for rent:<h1>
    <div class="card-container flex-wrap" style="display: flex; justify-content: space-between">
        <% @superpowers.each do |superpower| %>
          <% if superpower.photo.attached? %>  
            <div class="card my-4" id="card" style="flex: 0 0 30%; position: relative; background: linear-gradient(75deg, rgba(65,65,65,0.1) 0%, rgba(65,65,65,0.4) 42%, rgba(30,30,30,0.4) 100%), url('<%= cl_image_path superpower.photo.key %>');">
          <% else %> 
            <div class="card my-4" id="card" style="flex: 0 0 30%; position: relative; background: linear-gradient(75deg, rgba(65,65,65,0.1) 0%, rgba(65,65,65,0.4) 42%, rgba(30,30,30,0.4) 100%), url(<%= superpower.pic %>);">
          <% end %> 
            <h2 class="card-header"> <%= superpower.name %> </h2>
            <p class="card-description"><%= superpower.description %></p>
            <div class="card-price">
              <h3><%= superpower.price %> € / Day</h3>
              <p class="card-user-link">BY: <%= "#{Faker::Name.name}" %></p>
            </div>
            <%= link_to "", superpower_path(superpower), class: "card-link" %>
          </div>
        <% end %>
    </div>
  </div>
  <h1>You pending reservations:</h1>
  <table class="table">
      <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Superpower</th>
      <th scope="col">From:</th>
      <th scope="col">Until:</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
      <% @superpowers.each do |superpower| %>
        <% superpower.rents.each do |rent|  %>
          <tr>
          <th scope="row"> <%= rent.id %> </th>
          <td><%= rent.superpower.name %></td>
          <td> <%= rent.date_from %> </td>
          <td> <%= rent.date_to %> </td>
          <td>  <% if rent.status %> 
                 confirmed
                <% else %>
                <%= link_to 'To confirm', rent_path(rent), method: 'patch', anchor: 'Scroll-here', remote: true %>
               <% end %></td>
          <td> <%= link_to '☠️ Delete ', rent_path(rent), method: :delete %> </td>
          </tr>
        <% end  %>
      <% end %>
      </table>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rents/index.html.erb
<div class="container text-center">
  <br>
  <br>
  <br>
  <h1>Here are your booked powers:</h1>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Superpower</th>
      <th scope="col">From:</th>
      <th scope="col">Until:</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
 
 <% @rents.each do |rent| %>
     <tr>
      <th scope="row"> <%= rent.id %> </th>
      <td><%= rent.superpower.name %></td>
      <td> <%= rent.date_from %> </td>
      <td> <%= rent.date_to %> </td>
      <td> <%= rent.status ? "confirmed" : "pending" %> </td>
      <td> <%= link_to "☠️ Delete ", rent_path(rent), method: :delete %> </td>
    </tr>
 <% end %>
 
  <br>
  <h6><%= link_to "Go back to Superpowers", superpowers_path %></h6>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright <i class="fas fa-heart"></i> to Lea, Illia, Valeria & Marius
  </div>
</div>

app/views/shared/_form_superpower.html.erb
<div class="container w-50">
  <%= simple_form_for @superpower do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-primary mt-2" %> 
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/superpowers", class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/superpowers", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "demodaypicture.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", "/superpowers/:superpower_id/rents", class: "dropdown-item" %>
            <%= link_to "Create a new Superpower", new_superpower_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/superpowers/_info_window.html.erb
<div class="info-window">
  <h2><%= link_to superpower.name, superpower_path(superpower) %></h2>
  <p><%= superpower.location %></p>
</div>

app/views/superpowers/edit.html.erb
<!-- used often which is why it's being rendered from the shared file -->
<%= render 'shared/form_superpower', superpower: @superpower %>

app/views/superpowers/index.html.erb
<div class="banner">
      <div class="banner-wrapper">
        <h1>BROWSE ALL SUPERPOWERS</h1>
        <p>Find the superpower that fits you</p>
        <%= form_tag superpowers_path, method: :get do %>
          <%= text_field_tag :query,
                             params[:query],
                             class: "form-control",
                             placeholder: "Find a superpower" %>
          <%= submit_tag "Search", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
</div>

<div class="container text-center">

  <div class="card-container flex-wrap" style="display: flex; justify-content: space-between">
    <% @superpowers.each do |superpower| %>
      <% if superpower.photo.attached? %>  
        <div class="card my-4" id="card" style="flex: 0 0 30%; position: relative; background: linear-gradient(75deg, rgba(65,65,65,0.1) 0%, rgba(65,65,65,0.4) 42%, rgba(30,30,30,0.4) 100%), url('<%= cl_image_path superpower.photo.key %>');">
      <% elsif superpower.pic %> 
        <div class="card my-4" id="card" style="flex: 0 0 30%; position: relative; background: linear-gradient(75deg, rgba(65,65,65,0.1) 0%, rgba(65,65,65,0.4) 42%, rgba(30,30,30,0.4) 100%), url(<%= superpower.pic %>);">
      <% else %>
        <div class="card my-4" id="card" style="flex: 0 0 30%; position: relative; background: linear-gradient(75deg, rgba(65,65,65,0.1) 0%, rgba(65,65,65,0.4) 42%, rgba(30,30,30,0.4) 100%), url('https://images.unsplash.com/photo-1601790189147-a6213f4feb9b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');">
      <% end %> 
        <h2 class="card-header"> <%= superpower.name %> </h2>
        <p class="card-description"><%= superpower.description %></p>
        <div class="card-price">
          <h3><%= superpower.price %> € / Day</h3>
          <p class="card-user-link">BY: <%= "#{Faker::Name.name}" %></p>
        </div>
        <%= link_to "", superpower_path(superpower), class: "card-link" %>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
  <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>
</div>

app/views/superpowers/new.html.erb
<%= render 'shared/form_superpower', superpower: @superpower %>

app/views/superpowers/show.html.erb
<div class="container text-center">
    <div id="showcard">
        <% if @superpower.photo.attached? %>
          <img src="<%= cl_image_path @superpower.photo.key %>" alt="">
        <% else %>
          <img src="https://images.unsplash.com/photo-1601790189147-a6213f4feb9b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
        <% end %>
        <h2 class="showcard-header"> <%= @superpower.name %> </h2>
        <p class="showcard-description"><%= @superpower.description %></p>
        <div class="showcard-price">
          <h3><%= @superpower.price %> € / Day</h3>
        </div>
    </div>

  <div class="book_it">
      <h2 class="text-center">BOOK YOUR POWER</h2>
       <%= simple_form_for [@superpower, @rent] do |f| %>
        <%= f.input :date_from, as: :string, required: true, input_html: { class: "datepicker" } %>
        <%= f.input :date_to, as: :string, required: true, input_html: { class: "datepicker" } %>
        <%= f.button :submit, "BOOK IT", class: "btn btn-danger w-100 mb-4" %>
      <% end %>
  </div>
<div class="container">
  <div id="map"
      style="border: 1px solid white; box-shadow: none; z-index: 1; width: 56%; height: 400px; margin: 60px 200px 60px 485px; border-radius: 16px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>
</div>

app/views/users/show.html.erb
<%#= cl_image_tag @user.photo.key %>
<div class="container text-center">
  <div class="image my-5">
   <%= cl_image_tag "user_pic_default", width: 70, height: 70, crop: :scale, radius: :max %>
  </div>
  <h1>User:</h1>
  <h2><%= @user.email %></h2>
</div>